name: gbkyc
description: Flutter SDK.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  camera: ^0.9.8
  camera_android: 0.9.7+1
  camera_avfoundation: 0.9.7+1
  device_info_plus: ^3.2.1
  dio: ^4.0.0
  dotted_border: ^2.0.0
  dropdown_button2: ^1.6.1
  encrypt: ^5.0.1
  equatable: ^2.0.3
  flutter_bloc: ^7.3.3
  flutter_dotenv: ^5.0.2
  flutter_easyloading: ^3.0.3
  flutter_iconly:
  get: ^4.6.1
  # google_mlkit_text_recognition: ^0.3.0
  http: ^0.13.4
  image: ^3.1.1
  image_cropper: ^2.0.2
  image_gallery_saver: ^1.7.0
  image_picker: ^0.8.4
  intl: ^0.17.0
  loading_indicator: ^3.0.2
  mask_text_input_formatter: ^2.0.0
  path_provider: ^2.0.2
  permission_handler: ^9.2.0
  pin_code_fields: ^7.4.0
  responsive_framework: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ntc.gbkyc
        pluginClass: GbkycPlugin
      ios:
        pluginClass: GbkycPlugin

  fonts:
    - family: kanit
      fonts:
        - asset: packages/gbkyc/fonts/Kanit-Regular.ttf
        - asset: packages/gbkyc/fonts/Kanit-Bold.ttf
          weight: 700

  assets:
    - assets/icons/
    - assets/images/
    - assets/terms_of_service_en.txt
    - assets/terms_of_service_th.txt
    - assets/thai-province-data.json
    - assets/.env
